### ISSUE TITLE
Use .number modifier on v-model instances

### ISSUE THREAD

**Issue by marlanperumal** [samperumal/covid#14]
The `.number` [modifier](https://vuejs.org/v2/guide/forms.html#number) allows for the attached model to be controlled without an explicit type-cast. This should make the code a bit cleaner and prevent typo errors, when forgetting to cast

**Comment by samperumal** [comment]
That's cool, didn't know about it. I'm using `null` to indicate no value, and it appears to work with that as well. Even cooler.

**Comment by samperumal** [comment]
Fixed in vuex-branch. Left numeric checks in code for now.
